### ISSUE TITLE
definition of epsilon in VAE

### ISSUE THREAD

**Issue by pporridge** [dthuff/pet-vae#2]
Thanks for sharing the code, it helps me a lot. I've tried to train the model and encountered with a problem that loading model weight for testing may cause wrong reconstruction results even the validation shows pretty well. I was wondering whether it was due to the definition of epsilon in init part of VAE. Epsilon has been fixed since the model was defined.

**Comment by dthuff** [comment]
Hi! Glad to hear someone is using the code. I've opened a PR that I think addresses this. See changes to `save_load.py` in the linked PR. I'm retraining today to make sure this addresses the issue and will merge and close if it does. Feel free to test on your end as well.
